#!/bin/bash
set -e
set -u

rm sedargs || true
mkfifo -m 0600 sedargs

passwd=`gpg --decrypt ~/.mutt/passwd`

# Functions
provide_sedargs() 
{
  for line in $passwd
  do
    prefix=`echo $line | cut -d'|' -f1`
    uname=`echo $line | cut -d'|' -f2`
    pass=`echo $line | cut -d'|' -f3-`

    echo 's/#\{3\}'"$prefix"'-uname#\{3\}/'"$uname"'/' >> sedargs
    echo 's/#\{3\}'"$prefix"'-pass#\{3\}/'"$pass"'/' >> sedargs
  done

  unset prefix
  unset uname
  unset pass
  unset line
}

provide_config()
{
  cat "$1" | sed -f sedargs > "${1%-template}"
}

provide_sedargs &

templates=`find . -type f -name "*-template"`
for t in $templates
do
  rm ${t%-template} || true
  mkfifo -m 0600 "${t%-template}"
  provide_config "$t" &
done

mutt

rm sedargs
for t in $templates
do
  rm "${t%-template}" || true
done
